### ISSUE TITLE
关于run app阶段的问题

### ISSUE THREAD

**Issue by Huangzisu** [fsy2001/fudan-sport-automate#12]
在run app的时候报错：
<img width="646" alt="6789ec4db370a38850589e73c2e1595" src="https://user-images.githubusercontent.com/113163734/230820037-81a1f2ac-fc6e-4011-b811-4357c0888e01.png">

**Comment by fsy2001** [comment]
之前的版本有bug，已经修复了，请更新一下版本

**Comment by Huangzisu** [comment]
> 之前的版本有bug，已经修复了，请更新一下版本

okok，谢谢您
