### ISSUE TITLE
关于运行失败的问题

### ISSUE THREAD

**Issue by Jeremy112358** [fsy2001/fudan-sport-automate#13]
为什么workflow失败当中显示Process completed with exit code 1？

**Comment by Jeremy112358** [comment]
run app阶段显示ERROR (start): device 为必传参数

**Comment by lrlbb05** [comment]
<img width="1154" alt="Screen Shot 2023-04-10 at 16 46 37" src="https://user-images.githubusercontent.com/129683167/230867378-02956cd8-1c59-42e9-b4e8-3f4f02983bc3.png">

**Comment by Huangzisu** [comment]
> run app阶段显示ERROR (start): device 为必传参数

貌似刚刚修完bug，可以update一下再试试

**Comment by Jeremy112358** [comment]
OK谢谢

**Comment by fsy2001** [comment]
这是之前版本的bug，请更新到新版本

**Comment by born-125** [comment]
![Screenshot_20230410_210129_com tencent androidqqmail](https://user-images.githubusercontent.com/130303097/230906267-cf79e912-8daa-40d5-b1c0-a06dcfe0bdb3.jpg)
请问出现这种情况应该怎么办呢

**Comment by lrlbb05** [comment]
更新到最新版手动再run一下试试？

> ![Screenshot_20230410_210129_com tencent androidqqmail](https://user-images.githubusercontent.com/130303097/230906267-cf79e912-8daa-40d5-b1c0-a06dcfe0bdb3.jpg)
> 请问出现这种情况应该怎么办呢

**Comment by fsy2001** [comment]
请更新仓库到最新版本，更新方法参考 README 中的说明：

> 在自己复制的仓库上方可以看到一条提示：This branch is * commits behind ***，点击 Sync fork，然后点击 Update branch 即可同步到最新版本。

**Comment by born-125** [comment]
好的，感谢

**Comment by walxn** [comment]
> 

OK谢谢！
