### ISSUE TITLE
程序运行失败

### ISSUE THREAD

**Issue by lyciaatic** [fsy2001/fudan-sport-automate#18]
一直是按照教程设置的，也有修改过，但一直运行失败
![image](https://user-images.githubusercontent.com/130490073/232381860-f884655d-ffb0-49b4-bf73-911935710d5a.png)

**Comment by pearl-qaq** [comment]
我也是一直失败，请问怎么解决的呀

**Comment by fsy2001** [comment]
说明你的Token输入的不正确，请再次抓包检查Token，确保没有多余的空格/换行/特殊符号被输入。Token应该全部由字母/数字组成。

**Comment by lyciaatic** [comment]
> 
谢谢解答，我昨天意识到输的token有问题已经解决啦
