### ISSUE TITLE
想问一下抓包在iPhone上 ，然后github运行在mac电脑上是可以的吗？还是一定要在同一个设备上 求🥹🥹🥹🥹🥹🥹🥹🥹

### ISSUE THREAD

**Issue by Lop11111** [fsy2001/fudan-sport-automate#20]

**Comment by fsy2001** [comment]
不需要，你抓到的 Token 在任何地方都可以直接用

**Comment by Lop11111** [comment]
请问运行失败 有个红色的❌然后写了 run app 是什么意思？ up我是不是只需要把抓包弄好 然后项目复制然后运行就行了？我晕了🥲🥲🥲🥲

**Comment by fsy2001** [comment]
红色的叉说明你运行失败了，可能是相关信息没有填写完全。
项目复制后还需要填写Secret，我在README里已有相关说明，请你遵照README里的说明依次执行。

**Comment by Lop11111** [comment]
up 再麻烦你 我把secret也都写了 为什么运行还是失败。 user ID和token都是写了。感谢感谢 🙏

**Comment by Lop11111** [comment]
它显示的是 Process completed with exit code 1.  真的麻烦您再回答一下我的问题 谢谢谢谢谢谢

**Comment by fsy2001** [comment]
我看了你的提示，写的是Token错误，请你再次检查自己的Token填写是否正确，Token一般由字母和数字组成，确保你的Token中没有包含 & 或空格等特殊符号

**Comment by fsy2001** [comment]
由于你没有回复，我先将这个话题关闭了，如果仍有问题可以另开话题求助
