### ISSUE TITLE
密匙

### ISSUE THREAD

**Issue by Amamksjs** [fsy2001/fudan-sport-automate#21]
请问secret的值是哪两个数字呀

**Comment by fsy2001** [comment]
Secret 要设置两个，名字分别为 `USER_ID` 和 `FUDAN_SPORT_TOKEN`，值是你自己用小程序抓包得到的，每个人的值都是不一样的，抓包方法请参考教程。

**Comment by Amamksjs** [comment]
明白啦，谢谢！
