### ISSUE TITLE
关于无法运行的问题

### ISSUE THREAD

**Issue by Amamksjs** [fsy2001/fudan-sport-automate#23]
<img width="960" alt="屏幕截图 2023-04-20 202809" src="https://user-images.githubusercontent.com/131112306/233366786-557bda2d-1d57-4e04-868a-cdd25466d6bf.png">
运行后一直显示是这个问题，请问要怎么解决呀

**Comment by Amamksjs** [comment]
确认了很多遍没有问题呀

**Comment by fsy2001** [comment]
这里不方便发你的隐私信息，你愿意的话可以把User ID和Token发到我的邮箱fsy2001@outlook.com让我跑一下试试
