### ISSUE TITLE
关于程序运行报错

### ISSUE THREAD

**Issue by lkx2005** [fsy2001/fudan-sport-automate#24]
运行的时候出现'Connection to sport.fudan.edu.cn timed out. (connect timeout=None)'怎么办啊

**Comment by fsy2001** [comment]
使用GitHub Action自动运行的话，连接不上复旦服务器是偶发的网络故障，如果发生重试即可。我检查了你的运行记录，你第二次重试不在早锻有效刷锻时间内，所以报错。你可以等待刷锻开放后重试，如仍有问题可以回复此issue。

**Comment by fsy2001** [comment]
使用GitHub Action自动运行的话，连接不上复旦服务器是偶发的网络故障，如果发生重试即可。我检查了你的运行记录，你第二次重试不在早锻有效刷锻时间内，所以报错。你可以等待刷锻开放后重试，如仍有问题可以回复此issue。

**Comment by lkx2005** [comment]
谢谢解答，我重新试了一遍可以了
