### ISSUE TITLE
网络错误

### ISSUE THREAD

**Issue by WIllField7** [fsy2001/fudan-sport-automate#25]
Error: Process completed with exit code 1. 这个怎么解决啊

**Comment by WIllField7** [comment]
<img width="1280" alt="bf5f96dc4efd1598b412cfd9ba5fb27" src="https://user-images.githubusercontent.com/131889729/234764510-20fec173-18bb-4525-b497-b036207b34c8.png">

**Comment by fsy2001** [comment]
这可能是偶发的网络错误，可以在下一个刷锻时间重试。
