### ISSUE TITLE
修改workflow目录名导致报错

### ISSUE THREAD

**Issue by shkvdjs** [fsy2001/fudan-sport-automate#26]
显示的是The 'shkvdjs/fudan-sport-automate' repository doesn't contain the '.github/workflows/evening.yaml' path in 'main'.

**Comment by fsy2001** [comment]
你把 `.github/workflow` 目录改成 `.github/工作流` 了。GitHub Action只能识别 `.github/workflow` 下的配置文件，不要修改此目录名称。
