### ISSUE TITLE
在run app那边失败了

### ISSUE THREAD

**Issue by guhuaaa** [fsy2001/fudan-sport-automate#27]
之前每一步都是按照教程完成的，但是到了刷段时间收到了报错邮件，查看显示run app这一步出错了
![微信图片_20230505140547](https://user-images.githubusercontent.com/132547512/236387363-09bbeea2-5a3a-4cab-8427-7d22792cbc66.png)

**Comment by douwenxi** [comment]
run app步骤一般是多长时间是对的，我这里run了十分钟，还没好

**Comment by fsy2001** [comment]
在服务器上运行时间不能保证，因为服务器可能会在任意时刻暂停执行，一般需要10-30分钟，如果需要精确控制时间可以选择本地运行。
