### ISSUE TITLE
没法自动刷锻

### ISSUE THREAD

**Issue by CainCairn** [fsy2001/fudan-sport-automate#28]
都按步骤做了一遍，但到了时间没法自动刷锻，需要我手动开启。请问是什么问题？

**Comment by fsy2001** [comment]
首先，Fork 后的 Action 默认是停用的，需要手动 enable，这点在教程中已有说明。其次，你的仓库中的运行记录显示你今天早上有一次自动刷锻记录，而前两天是周末，默认不会自动刷锻，也有可能是这个原因。
