### ISSUE TITLE
自动运行时run app过程出现问题

### ISSUE THREAD

**Issue by Bloodredbromine** [fsy2001/fudan-sport-automate#30]
run app在约4min后自动终止导致刷锻失败，如图
![_%M8%M(TKSHY7ZYXDA$V1%R](https://user-images.githubusercontent.com/132531098/236832343-b85b7509-fb41-4c26-b402-b3bd18c7e53f.png)

**Comment by fsy2001** [comment]
是偶发错误，已修改错误处理逻辑

**Comment by Bloodredbromine** [comment]
今天早上又出现同样的问题了。。
![Uploading JM9L1$4J2SM`U34MCT@27VJ.png…]()
