### ISSUE TITLE
关于程序运行失败的问题

### ISSUE THREAD

**Issue by ccgk-Zhy** [fsy2001/fudan-sport-automate#31]
![image](https://user-images.githubusercontent.com/131571478/236832458-ef6daf8b-769f-4564-9ad0-c0dd36cacb15.png)

**Comment by cesoiroujemais** [comment]
一样的情况555555

**Comment by fsy2001** [comment]
可能是程序bug，之后会调查此问题。

**Comment by fsy2001** [comment]
是偶发故障，已经修改了错误处理逻辑。
