### ISSUE TITLE
刷段程序报错

### ISSUE THREAD

**Issue by jxycyza** [fsy2001/fudan-sport-automate#33]
总是出现[evening-exercise](https://github.com/jxycyza/fudan-sport-automate/actions/runs/4915339462/jobs/8777719039#step:5:29)
Process completed with exit code 1.
![Screenshot_20230508_220153](https://user-images.githubusercontent.com/131886662/236844559-fd4c875a-e81c-4fb3-8355-e3dc66569775.jpg)

**Comment by fsy2001** [comment]
可能是程序bug，之后会调查此问题

**Comment by fsy2001** [comment]
应该是偶发错误，服务器返回了不符合预期的内容，已经修改了错误处理逻辑
