### ISSUE TITLE
时长过长

### ISSUE THREAD

**Issue by cesoiroujemais** [fsy2001/fudan-sport-automate#34]
刷锻显示成功，但程序运行时长为32m 5s，小程序里面看到的锻炼记录用时也是32分钟，请问为什么时间会变得这么长呀？

**Comment by fsy2001** [comment]
这是由于 GitHub Actions 执行期间排队导致的，服务器可能会在运行过程中暂停脚本的执行，因此无法控制脚本的运行时间。您可以通过在本地运行脚本来准确控制运行时间。
