### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by yangy5443** [fsy2001/fudan-sport-automate#36]
UPDATE: 操作成功 (258.82306963010467m / 1223.3830837677185m)
UPDATE: 操作成功 (262.2740438918394m / 1223.3830837677185m)
UPDATE: 操作成功 (265.7250181535742m / 1223.3830837677185m)
UPDATE: 操作成功 (269.175[99](https://github.com/yangy5443/fudan-sport-automate/actions/runs/4915006112/jobs/8776983879#step:5:100)241530894m / 1223.3830837677185m)
UPDATE: 操作成功 (272.6269666770437m / 1223.3830837677185m)
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.
运行workflow 文件时我在小程序中刷新可以看到正在刷锻，因此id和token没问题。我检查了一遍id和token确实是没问题。我不知道问题出在哪

**Comment by Daviiidd913** [comment]
我也是，好崩溃

**Comment by fsy2001** [comment]
这是服务器返回了格式不正确的数据，目前猜测属于偶发故障，我之后会调查原因并修改错误处理逻辑

**Comment by fsy2001** [comment]
已修改

**Comment by Saka7777** [comment]
早锻和下午锻正常，晚锻经常出现这个是怎么回事
