### ISSUE TITLE
自动运行的actions不在打卡时间段

### ISSUE THREAD

**Issue by cesoiroujemais** [fsy2001/fudan-sport-automate#37]
您好！请问自动运行的actions为什么会不在打卡时间段呀？我看到今晚的夜跑是在21：39运行的，但打卡时间段是18：00-21：00
运行记录截图如下：
https://github.com/fsy2001/fudan-sport-automate/assets/132743489/7470c76d-ba77-4ccd-b71e-a332749a774b
https://github.com/fsy2001/fudan-sport-automate/assets/132743489/b3318661-b9cf-4b0b-9536-b5b100f6cc56

**Comment by fsy2001** [comment]
这可能是因为GitHub Actions将您的任务排队延迟运行了。这是使用GitHub Actions时无法避免的。您可以在指定时间手动触发workflow或者在本地运行Python脚本来避免。
