### ISSUE TITLE
mac环境变量配置一直失败怎么办感谢

### ISSUE THREAD

**Issue by LXY020414** [fsy2001/fudan-sport-automate#5]

**Comment by fsy2001** [comment]
在macOS上打开终端，输入 `export USER_ID=<抓包得到的user id>`，`export FUDAN_SPORT_TOKEN=<抓包得到的token>`，每行输入完成后需要按回车执行。要检查是否设置成功，输入 `echo $USER_ID`，`echo $FUDAN_SPORT_TOKEN` 即可，如果设置成功，则 `echo` 命令会输出刚刚设置的环境变量。设置完成后，**在设置环境变量的终端内**运行本项目的 Python 脚本。在关闭当前终端窗口后，环境变量就会失效。

如果希望每次打开终端都能自动设置环境变量，可以执行命令 `touch ~/.zshrc; open -t ~/.zshrc`，在弹出的编辑器里输入之前提到的两行 `export` 命令，然后重启终端即可生效。
