### ISSUE TITLE
关于脚本的运行

### ISSUE THREAD

**Issue by 774Ryan** [fsy2001/fudan-sport-automate#6]
请问按照您readme中的提示在github中配置好环境变量以后就不用其他操作了嘛？（除了每3天改一次token）
readme的使用标题下的那些操作是不是不需要进行呢？
谢谢！！！

**Comment by devolous** [comment]
只需要两个操作：
1. 配置环境变量
2. 在Actions选项卡下点击绿色的 "I understand……" 来允许workflow运行

**Comment by 774Ryan** [comment]
好的，完成啦！太感谢您了！

**Comment by born-125** [comment]
这个脚本需要第三天都更新一下吗

**Comment by fsy2001** [comment]
> 这个脚本需要第三天都更新一下吗

每三天抓一下包，更新一下 Secret
