### ISSUE TITLE
关于抓包软件设置

### ISSUE THREAD

**Issue by brandfucker** [fsy2001/fudan-sport-automate#7]
需要把fidder中https部分设置的那个复选框由 from browers only 改为 from all processes ,教程链接中很容易看漏。

另外路程随机数范围可能最好麻烦再设大一点，一米上下浮动还是有点可疑。

**Comment by brandfucker** [comment]
另外非常感谢作者开源代码！您是我们懒狗的救命恩人！

**Comment by fsy2001** [comment]
已在README中更新
